### ISSUE TITLE
Failed building wheel for editdistance  in Win10 

### ISSUE THREAD

**Issue by dbsxdbsx** [SerpentAI/SerpentAI#54] opened 2017-09-26 15:01 UTC
I am with win10, and I personally installed cuda, cudnn and VS2017 community version.
According to the installation for windows from Wiki, for the last step after inputing "serpent setup"
first it output:
`It appears that the setup process had already been performed. Are you sure you want to proceed? Some important files will be overwritten! (One of: 'YES', 'NO'): `
Then I input YES, then it output :
`Which backend do you plan to use for Tensorflow (One of: 'CPU', 'GPU' - Note: GPU backend can only be used on NVIDIA GTX 600 series and up):`
I input GPU ,though I don't  want to use tensorflow...
Then after installing some pachage, error occurs:

```
 Running setup.py bdist_wheel for editdistance ... error
  Failed building wheel for editdistance
  Running setup.py clean for editdistance
  Running setup.py bdist_wheel for hiredis ... error
  Failed building wheel for hiredis
  Running setup.py clean for hiredis
```
for error with hiredis , I solved it by `pip install hiredis `, but for editdistance, I can't solve it this way, neither for `conda install editdistance` nor `easy_install editdistance`.       
after solving hiredis ,and typing in "serpent setup" again, it raised error like this:
`Could not find a version that satisfies the requirement editdistance (from -r requirements.txt (line 32)) (from versions: )
No matching distribution found for editdistance (from -r requirements.txt (line 32))`
Then I googled, I did found some way to solve it by manually download this wheel and manually edit some file related to this wheel.  But here in  "serpent" environment,  I have no idea how to solve it. 
Hope someone could help me, thanks.

**Comment by nbrochu** [comment] 2017-09-26 15:25
Duplicate of #25 - Still looking for someone with enough expertise with building C++ packages in Windows  to help.

**Closed by nbrochu** 2017-09-26 15:25 UTC
